In [1]:
import pandas as pd
import glob
import os
import warnings
warnings.filterwarnings("ignore")


FILE_PATH = os.path.expanduser("~/git/dataport/metadata/electricity_egauge_hours/")
METADATA_PATH = os.path.expanduser("~/git/dataport/metadata/metadata.csv")
# HDF_PATH = os.path.expanduser("~/monthly-12-17.h5")

In [83]:
survey_path_13 = "../metadata/survey_2013_all_participants.csv"
survey_path_14 = "../metadata/survey_2014_all_participants.csv"

In [84]:
df_13 = pd.read_csv(survey_path_13)
df_14 = pd.read_csv(survey_path_14)

In [93]:
columns = ['dataid', 'year_house_constructed', 'house_num_rooms', 'house_square_feet', 'house_ceiling_height', 
           'ethnicity_asian_pacific_islander', 'ethnicity_black_african_american', 'ethnicity_caucasian_other_than_hispanic_or_latino',
          'ethnicity_hispanic_or_latino', 'ethnicity_native_american_alaska_native', 'ethnicity_other', 'ethnicity_decline',
          'sex_males', 'sex_females', 'residents_under_5', 'residents_6_to_12', 'residents_13_to_18', 'residents_19_to_24', 
           'residents_25_to_34', 'residents_35_to_49', 'residents_50_to_64', 'residents_older_65', 'education_level', 'total_annual_income',
          'ceiling_fans_count']

In [94]:
raw_df_13 = df_13.iloc[:, df_13.columns.isin(columns)]
raw_df_14 = df_14.iloc[:, df_14.columns.isin(columns)]

In [104]:
set_13 = set(raw_df_13[['dataid']].values.reshape(1, -1)[0])
set_14 = set(raw_df_14[['dataid']].values.reshape(1, -1)[0])

In [114]:
import numpy as np
data = np.load("./data-2013-2017-missing.npy").item()

In [117]:
data[2013].keys()

dict_keys([9121, 2818, 1283, 4357, 8967, 1800, 5129, 6412, 2829, 6673, 5395, 4373, 6423, 26, 6941, 7429, 4641, 4135, 9771, 6910, 2094, 1185, 2864, 3635, 7989, 1334, 624, 4154, 9019, 5949, 1601, 1718, 6990, 1103, 7504, 2129, 739, 5972, 86, 7769, 9052, 93, 94, 3935, 4193, 5218, 9915, 9830, 871, 7016, 1642, 2156, 2158, 7536, 370, 3192, 2171, 8317, 3967, 3456, 2945, 898, 3719, 9609, 3723, 9356, 2242, 1169, 7875, 8084, 8597, 2199, 3224, 5785, 410, 5275, 3482, 2974, 1953, 3918, 2470, 1192, 7850, 5746, 4526, 3504, 4447, 5814, 7863, 6072, 2233, 7866, 187, 9919, 7361, 9922, 2755, 9926, 3527, 9160, 9929, 545, 9933, 4302, 1464, 9939, 2638, 8155, 8669, 3039, 8419, 9701, 2769, 744, 3367, 6636, 5357, 8829, 7731, 5874, 2814, 1782, 5615, 9654, 5371, 9982, 6101])

In [120]:
raw_df_13

,dataid,year_house_constructed,house_num_rooms,house_square_feet,house_ceiling_height,ethnicity_asian_pacific_islander,ethnicity_black_african_american,ethnicity_caucasian_other_than_hispanic_or_latino,ethnicity_hispanic_or_latino,ethnicity_native_american_alaska_native,...,residents_6_to_12,residents_13_to_18,residents_19_to_24,residents_25_to_34,residents_35_to_49,residents_50_to_64,residents_older_65,education_level,total_annual_income,ceiling_fans_count
0,43,1973,8.0,1500.0,8,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,College graduate,$10-000 - $19-999,6.0
1,1629,1992,10.0,2335.0,10,NaN,NaN,NaN,Hispanic,NaN,...,NaN,1.0,1.0,NaN,2.0,NaN,NaN,Postgraduate degree,$100-000 - $149-999,5.0
2,2053,1930 or earlier,5.0,1050.0,11 ft.,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Postgraduate degree,$20-000 - $34-999,6.0
3,4517,1975,8.0,1600.0,8,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,College graduate,$20-000 - $34-999,4.0
4,1600,1939,8.0,1575.0,8.5,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,Postgraduate degree,$100-000 - $149-999,4.0
5,2836,1999,5.0,3400.0,9,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,College graduate,$150-000 - $299-000,6.0
6,2242,1999,4.0,3500.0,10,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Postgraduate degree,NaN,6.0
7,3394,1978,8.0,2800.0,9,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Some college/trade/vocational school,$150-000 - $299-000,6.0
8,5371,1941,6.0,980.0,9,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,Postgraduate degree,$100-000 - $149-999,4.0
9,2557,1965,16.0,3300.0,8 ft,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,Postgraduate degree,$100-000 - $149-999,6.0
10,2257,2002,8.0,4100.0,96,NaN,NaN,Caucasian,NaN,NaN,...,1.0,NaN,NaN,NaN,2.0,NaN,NaN,Some college/trade/vocational school,$100-000 - $149-999,5.0
11,5490,1964,9.0,1850.0,8,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,Postgraduate degree,$100-000 - $149-999,3.0
12,626,2006,6.0,NaN,10,NaN,NaN,NaN,Hispanic,NaN,...,1.0,NaN,NaN,1.0,NaN,NaN,NaN,College graduate,$20-000 - $34-999,4.0
13,7866,1987,4.0,1100.0,8,NaN,NaN,NaN,Hispanic,NaN,...,NaN,NaN,NaN,NaN,3.0,NaN,NaN,Postgraduate degree,$75-000 - $99-999,5.0
14,5288,2000,7.0,3200.0,16,NaN,NaN,NaN,Hispanic,NaN,...,NaN,NaN,1.0,NaN,NaN,2.0,NaN,College graduate,$150-000 - $299-000,6.0
15,5511,1981,6.0,1140.0,7,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Postgraduate degree,$100-000 - $149-999,1.0
16,1572,2007,8.0,2100.0,10,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Some college/trade/vocational school,$100-000 - $149-999,6.0
17,2297,2011,4.0,1500.0,8,NaN,NaN,NaN,Hispanic,NaN,...,2.0,1.0,NaN,2.0,NaN,NaN,NaN,Some college/trade/vocational school,$75-000 - $99-999,6.0
18,9605,1967,11.0,2200.0,8 ft,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,College graduate,$75-000 - $99-999,NaN
19,8223,1955,9.0,2300.0,8,NaN,NaN,Caucasian,NaN,NaN,...,NaN,2.0,NaN,NaN,2.0,NaN,NaN,High School graduate,$100-000 - $149-999,4.0
20,9931,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Hispanic,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,Some college/trade/vocational school,$20-000 - $34-999,4.0
21,2929,1950,3.0,1552.0,10?,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,College graduate,$100-000 - $149-999,4.0
22,5746,1950,9.0,1768.0,8,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,NaN,NaN,College graduate,$100-000 - $149-999,6.0
23,6787,1985,5.0,1600.0,varies from 8ft to 15ft,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,2.0,NaN,NaN,Postgraduate degree,$150-000 - $299-000,5.0
24,4342,1953,8.0,1316.0,8,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,College graduate,$75-000 - $99-999,4.0
25,4594,1975,7.0,2506.0,"96""",NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Some High School,NaN,6.0
26,1741,1999,6.0,1993.0,?,NaN,Black/African-American,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,1.0,Postgraduate degree,NaN,2.0
27,7332,2002,9.0,2850.0,11.5,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Postgraduate degree,NaN,5.0
28,5673,1980,6.0,1900.0,8 ft,NaN,NaN,Caucasian,NaN,NaN,...,3.0,NaN,NaN,1.0,1.0,NaN,NaN,College graduate,$100-000 - $149-999,4.0
29,4231,1975,14.0,4200.0,8,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,Postgraduate degree,$150-000 - $299-000,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,6139,1969,9.0,2800.0,9,NaN,NaN,Caucasian,NaN,NaN,...,2.0,0.0,0.0,0.0,2.0,0.0,0.0,Postgraduate degree,$150-000 - $299-000,6.0
290,2296,2000,9.0,3100.0,8,Asian/Pacific Islander,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,2.0,NaN,Postgraduate degree,$50-000 - $74-999,5.0
291,754,1991,9.0,1674.0,8,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,College graduate,$50-000 - $74-999,3.0
292,9080,NaN,12.0,2800.0,9,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,2.0,NaN,College graduate,$50-000 - $74-999,6.0
293,9080,2006,12.0,2800.0,8,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,2.0,NaN,College graduate,$50-000 - $74-999,6.0
294,5909,2012,1.0,670.0,NaN,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Postgraduate degree,$100-000 - $149-999,NaN
295,9775,2012,7.0,2300.0,9,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,College graduate,$75-000 - $99-999,2.0
296,5938,2013,3.0,1476.0,8 to 16,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Postgraduate degree,$100-000 - $149-999,1.0
297,7062,2013,4.0,1400.0,10,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,College graduate,$150-000 - $299-000,2.0
298,8061,2012,3.0,1600.0,12ft,NaN,NaN,Caucasian,NaN,Native American/Alaska Native,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,College graduate,$100-000 - $149-999,NaN
299,9983,1967,12.0,3000.0,8,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,Postgraduate degree,$100-000 - $149-999,6.0
300,2606,2012,4.0,1390.0,9 ft,Asian/Pacific Islander,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,College graduate,$100-000 - $149-999,NaN
301,8574,2012,3.0,1400.0,9,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,College graduate,$100-000 - $149-999,NaN
302,1731,2012,4.0,1555.0,16,NaN,NaN,Caucasian,NaN,NaN,...,0.0,NaN,0.0,1.0,NaN,1.0,NaN,College graduate,$75-000 - $99-999,NaN
303,8342,2013,3.0,1401.0,NaN,Asian/Pacific Islander,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,College graduate,$75-000 - $99-999,NaN
304,8342,2013,3.0,140.0,NaN,Asian/Pacific Islander,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,2.0,NaN,NaN,College graduate,$75-000 - $99-999,NaN
305,2412,2012,6.0,1800.0,25,NaN,NaN,Caucasian,NaN,NaN,...,NaN,2.0,NaN,1.0,1.0,NaN,NaN,College graduate,$150-000 - $299-000,NaN
306,3610,2002,10.0,2600.0,10,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,Some college/trade/vocational school,$100-000 - $149-999,4.0
307,9934,1970,8.0,2500.0,8,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,Postgraduate degree,$100-000 - $149-999,1.0
308,469,1995,13.0,2713.0,9,Asian/Pacific Islander,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,Postgraduate degree,$150-000 - $299-000,6.0
309,6308,1963,7.0,1200.0,7.5,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,College graduate,$20-000 - $34-999,2.0
310,7149,1979,9.0,3154.0,8 ft typical- 22 ft great room,NaN,NaN,NaN,Hispanic,NaN,...,NaN,1.0,NaN,1.0,NaN,2.0,NaN,College graduate,$100-000 - $149-999,6.0
311,3649,1973,7.0,2450.0,8,NaN,NaN,Caucasian,NaN,NaN,...,1.0,0.0,0.0,0.0,2.0,0.0,0.0,Postgraduate degree,$150-000 - $299-000,6.0
312,7645,1989,6.0,1800.0,10,NaN,NaN,Caucasian,NaN,NaN,...,1.0,1.0,NaN,NaN,2.0,NaN,NaN,Postgraduate degree,$100-000 - $149-999,6.0
313,9526,1999,13.0,2700.0,14,NaN,NaN,Caucasian,NaN,NaN,...,NaN,2.0,NaN,NaN,2.0,NaN,NaN,College graduate,$150-000 - $299-000,6.0
314,9922,2006,5.0,2300.0,138,NaN,NaN,Caucasian,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,Postgraduate degree,more than $1-000-000,6.0
315,9215,1971,7.0,2000.0,8ft,NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,College graduate,$100-000 - $149-999,4.0
316,4056,2001,12.0,2500.0,10,NaN,NaN,Caucasian,NaN,NaN,...,NaN,2.0,NaN,NaN,2.0,NaN,NaN,Postgraduate degree,$100-000 - $149-999,6.0
317,7769,1953,6.0,960.0,"8-0""",NaN,NaN,Caucasian,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,Postgraduate degree,$75-000 - $99-999,4.0
318,9647,2001,12.0,3100.0,9,NaN,NaN,Caucasian,NaN,NaN,...,2.0,0.0,0.0,0.0,1.0,1.0,0.0,Postgraduate degree,$150-000 - $299-000,6.0